CREATE TABLE migration_proposals (
    id UUID PRIMARY KEY,
    analysis_job_id UUID NOT NULL,
    project_issue_id UUID NOT NULL,
    rule_id VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    severity VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    file_path VARCHAR(1000) NOT NULL,
    start_line INT,
    end_line INT,
    original_content TEXT,
    original_content_hash VARCHAR(255),
    proposed_content TEXT,
    unified_diff TEXT,
    rationale TEXT,
    validation_status VARCHAR(50) NOT NULL,
    apply_status VARCHAR(50) NOT NULL,
    auto_fix_supported BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_migration_proposals_analysis_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id),
    CONSTRAINT fk_migration_proposals_project_issue FOREIGN KEY (project_issue_id) REFERENCES project_issues(id)
);
