package com.apianalyzer.analysis.domain.model.diff;
public enum ChangeType {
    ENDPOINT_ADDED, ENDPOINT_REMOVED,
    PARAMETER_ADDED, PARAMETER_REMOVED, PARAMETER_CHANGED,
    REQUEST_BODY_CHANGED, RESPONSE_ADDED, RESPONSE_REMOVED, RESPONSE_CHANGED,
    SCHEMA_PROPERTY_ADDED, SCHEMA_PROPERTY_REMOVED, SCHEMA_TYPE_CHANGED,
    ENUM_VALUE_ADDED, ENUM_VALUE_REMOVED,
    SECURITY_CHANGED
}
